# fly.toml app configuration file generated for mrhub on 2025-08-16T20:41:47-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mrhub'
primary_region = 'atl'
console_command = '/code/manage.py shell'

[build]

[env]
  PORT = '8000'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[statics]]
  guest_path = '/code/static'
  url_prefix = '/static/'

[[services.http_checks]]
  interval = "15s"
  timeout = "2s"
  method = "GET"
  path = "/health/"

[[http_service.checks]]
  interval = "10s"
  timeout = "2s"
  grace_period = "20s"
  method = "GET"
  path = "/storacha/health"

[deploy]
  release_command = "bash -lc 'python manage.py collectstatic --noinput'"
