services:
  - type: web
    name: iamhub-backend
    env: python
    buildCommand: ""
    startCommand: gunicorn iamhub_project.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: backend.iamhub_project.settings
      - key: SECRET_KEY
        value: your-secret-key
      - key: DEBUG
        value: False
