services:
  - type: web
    name: iamhub
    env: python
    region: oregon
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn iamhub.wsgi:application --preload --bind 0.0.0.0:$PORT
    autoDeploy: true
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        fromDatabase:
          name: iamhub-db
          property: connectionString
      - key: ALLOWED_HOSTS
        value: "iamhub.net,.onrender.com"
databases:
  - name: iamhub-db
    ipAllowList: []