# Generated by Django 5.2.5 on 2025-08-14 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="documentstamp",
            options={"ordering": ["-timestamped_at"]},
        ),
        migrations.AddField(
            model_name="contribution",
            name="verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="contribution",
            name="verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contribution",
            name="verify_txid",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
    ]
