# Generated by Django 5.2.5 on 2025-08-14 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_documentstamp_options_contribution_verified_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contribution",
            name="share_token",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="contribution",
            name="share_token_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="documentstamp",
            name="share_token",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="documentstamp",
            name="share_token_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="documentstamp",
            name="verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="documentstamp",
            name="verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="documentstamp",
            name="verify_txid",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
