services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: mrhub
      POSTGRES_USER: mrhub
      POSTGRES_PASSWORD: mrhub
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build: .
    command: bash -lc "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    working_dir: /code
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    volumes:
      - .:/code
    depends_on:
      - db

volumes:
  pgdata: