name: Mirror mrhub to knowledge-mirror

on:
  schedule:
    - cron: "*/10 * * * *"   # every 10 minutes
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      SRC_URL: git@github.com:Mr-Hub00/mrhub.git   # source via SSH
      SRC_BRANCH: knowledge                         # source branch to mirror
      TARGET_REPO: Mr-Hub00/knowledge-mirror        # target repo (this repo)
    steps:
      - name: Configure git identity
        run: |
          git config --global user.name "mirror-bot"
          git config --global user.email "mirror-bot@users.noreply.github.com"

      - name: Start ssh-agent (pinned SHA)
        uses: webfactory/ssh-agent@dc588b651fe13675774614f8e6a936a468676387
        with:
          ssh-private-key: ${{ secrets.SRC_DEPLOY_KEY }}

      - name: Clone source (non-bare)
        env:
          GIT_SSH_COMMAND: "ssh -v"
        run: |
          set -euo pipefail
          git clone "$SRC_URL" repo
          cd repo
          git fetch --all --prune
          git checkout "$SRC_BRANCH"

      - name: Remove workflow files on branch (avoid permissions block)
        run: |
          set -euo pipefail
          cd repo
          git rm -rf --ignore-unmatch .github/workflows || true
          if ! git diff --quiet; then
            git commit -m "[mirror] strip .github/workflows from ${SRC_BRANCH}"
          fi

      - name: Push to target (branch only)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail
          cd repo
          TARGET_URL="https://x-access-token:${GITHUB_TOKEN}@github.com/${TARGET_REPO}.git"

          if ! git remote | grep -qx target; then
            git remote add target "$TARGET_URL"
          else
            git remote set-url target "$TARGET_URL"
          fi

          echo "Pushing ${SRC_BRANCH} -> ${SRC_BRANCH} (force)…"
          git push target "${SRC_BRANCH}:${SRC_BRANCH}" --force
          echo "Done."
