name: Mirror mrhub -> knowledge-mirror

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

permissions:
  contents: write
  workflows: write

jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      SRC_URL: git@github.com:Mr-Hub00/mrhub.git
      TARGET_REPO: ${{ vars.TARGET_REPO }}

    steps:
      - name: Configure git identity
        run: |
          git config --global user.name "mirror-bot"
          git config --global user.email "mirror-bot@users.noreply.github.com"

      - name: Start ssh-agent (pinned)
        uses: webfactory/ssh-agent@dc588b651fe13675774614f8e6a936a468676387
        with:
          ssh-private-key: ${{ secrets.SRC_DEPLOY_KEY }}

      - name: Pre-flight debug
        run: |
          echo "SRC_URL=${SRC_URL}"
          echo "TARGET_REPO=${TARGET_REPO}"
          ssh -T git@github.com || true

      - name: Clone source as mirror (with debug)
        env:
          GIT_SSH_COMMAND: "ssh -v"
        run: |
          set -euo pipefail
          git clone --mirror "$SRC_URL" repo.git
          cd repo.git
          git rev-parse --is-bare-repository
          git remote -v
          git for-each-ref --count=20 --format='%(objectname:short) %(refname)'

      - name: Update from origin
        run: |
          set -euo pipefail
          cd repo.git
          git remote set-url origin "$SRC_URL"
          git remote update --prune
          git for-each-ref --count=20 --format='%(objectname:short) %(refname)'

      - name: Push to target (GITHUB_TOKEN) with debug
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail
          cd repo.git
          TARGET_URL="https://x-access-token:${GITHUB_TOKEN}@github.com/${TARGET_REPO}.git"
          if ! git remote | grep -qx target; then
            git remote add target "$TARGET_URL"
          else
            git remote set-url target "$TARGET_URL"
          fi
          git remote -v
          git push --mirror target

      - name: Post-push summary
        run: |
          cd repo.git
          git for-each-ref --count=20 --format='%(objectname:short) %(refname)'
          echo "Mirror job finished ✅"